name: topconsuite/scan-build-publish-public-repository
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SERVER: ${{ secrets.NUGET_SERVER }}

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    timeout-minutes: 60
    continue-on-error: true
    env:
      # Variáveis de ambiente específicas do job, se necessário (mas não para definir caminhos baseados em env global)
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      DOTNET_NOLOGO: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Versão atualizada
        with:
          fetch-depth: '0'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Etapa de instalação de pré-requisitos removida (Java e .NET 5 redundantes)
      # Se o SonarScanner falhar por falta de Java, descomente e ajuste a linha abaixo:
      # - name: Install Java (if needed for SonarScanner)
      #   run: sudo apt-get update && sudo apt-get install -y openjdk-17-jre

      - name: Install SonarScanner tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run SonarScanner analysis
        # Navega para o diretório do projeto ANTES de rodar os comandos
        working-directory: ./Telluria.Utils.Crud # Define o diretório de trabalho para os comandos seguintes
        run: |
          # Extrai a versão do .csproj (método original mantido)
          # Agora roda a partir do diretório Telluria.Utils.Crud
          export VERSION=$(grep '<AssemblyVersion>' Telluria.Utils.Crud.csproj | sed 's/<[^>]*>//g' | tr -d '[:space:]')
          echo "Detected Version: $VERSION"

          # Inicia o SonarScanner - os caminhos são relativos ao working-directory ou use /d:sonar.projectBaseDir=.
          dotnet sonarscanner begin \
            /k:"Telluria-Utils-.NET-CRUD-" \
            /v:"$VERSION" \
            /d:sonar.login="${{ env.SONAR_TOKEN }}" \
            /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" \
            /d:sonar.sources="." # Analisa o diretório atual (Telluria.Utils.Crud)

          # Builda o projeto (estamos no diretório do projeto)
          # A build pode ser feita aqui ou antes do begin, dependendo da necessidade de análise
          dotnet build Telluria.Utils.Crud.csproj --configuration Release --no-restore

          # Finaliza o SonarScanner
          dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

  nuget-publish:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    timeout-minutes: 60
    continue-on-error: true # Considere remover se uma falha no publish deve falhar o workflow
    env:
      # Define a variável de ambiente para desabilitar telemetria do .NET (opcional, boa prática em CI)
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      DOTNET_NOLOGO: 'true'
      PROJECT_PATH: Telluria.Utils.Crud/Telluria.Utils.Crud.csproj # Caminho do projeto relativo à raiz
      PACKAGE_OUTPUT_DIR: ./Telluria.Utils.Crud/package # Diretório de saída relativo à raiz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Versão atualizada

      # A action setup-dotnet foi REMOVIDA pois o contêiner já tem o .NET 8 SDK

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build project
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          # Remove diretório de pacote antigo, se existir
          rm -rf "${{ env.PACKAGE_OUTPUT_DIR }}"

          # Cria o pacote nuget especificando o projeto e a saída
          dotnet pack "${{ env.PROJECT_PATH }}" --configuration Release --output "${{ env.PACKAGE_OUTPUT_DIR }}" --no-build

      - name: Publish NuGet package
        run: |
          # Publica todos os pacotes .nupkg encontrados no diretório de saída
          dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg" --api-key "${{ env.NUGET_API_KEY }}" --source "${{ env.NUGET_SERVER }}" --skip-duplicate